### ISSUE TITLE
Sorting in Target Dropzone lost after config of ONDrop event

### ISSUE THREAD

**Issue by WouterKessener** [scottdurow/power-drag-drop#16]
https://user-images.githubusercontent.com/15956643/209138810-15f3537c-0b04-4459-9464-2c77302b8835.mp4

Looks like the onDrop event is messing with the sorting of the items in de target DropZone.

**Comment by scottdurow** [comment]
Hi @WouterKessener - thanks for logging this.

The problem is likely to be that you have not updated the column that is being used to sort by. You'll need to use the updated position in the CurrentItems to patch a column that you use to sort the rows using. 

When you patch the source records the control will re-render with what ever sort you give it, so it will need to reflect the updated position.

Hope this helps - and thank you again for your support.

Scott

**Comment by WouterKessener** [comment]
@scottdurow Aha yes yes.. thanks. Got it to work. Cannot really patch the real source record but by using collections it works like a charm. Had to add a little extra to the OnDrop event.  Created a small vid to explain myself and hopefully help others facing the samen 'issue'

https://user-images.githubusercontent.com/15956643/210221359-d75a3adc-bd1f-45ae-be36-37a54a478c26.mp4

Have a great one.

**Comment by scottdurow** [comment]
Thank you for the excellent information and all your support!
