### ISSUE TITLE
Gap between the mouse cursor and the item being dragged

### ISSUE THREAD

**Issue by Katzenbach123** [scottdurow/power-drag-drop#21]
Hi Scott,

I have noticed that there is a gap between the mouse cursor and the item being dragged while dragging the item. It seems the gap the greater as the Y coordinate gots bigger as well (picking items from the bottom of the list). Is it possible to make it somehow 0?

![image](https://user-images.githubusercontent.com/122178896/211168842-b7495100-eef0-49f3-a502-47f78de29dc1.png)

**Comment by scottdurow** [comment]
Hi @Katzenbach123 
This is usually caused by apps having the scale to fit setting turned on (in the display settings) or not being a tablet app.

The component requires a responsive tablet app (custom page) with scale to fit turned off.

Could you try turning off scale to fit and see if that fixes your issue?

Thanks!
Scott

**Comment by Katzenbach123** [comment]
Hi Scott,

I can confirm turning off Scale to Fit resolved the issue! Thanks for your prompt response! :)

Regards:
Katzenbach
