### ISSUE TITLE
DropZones lose items when they are in a Gallery after scroll

### ISSUE THREAD

**Issue by rsantos00** [scottdurow/power-drag-drop#22]
I'm trying to do some tests with DropZone inside a Gallery. I have placed a dropzone  in the item template of the gallery and configured the items of the gallery like:

ForAll(Sequence(10),
        {
            Id:Text(Value+1),
            Name:"Item " & Value,
            Zone:"zone" & Text(Value+1),
            Items:Table()
        }
    )

When I scroll the gallery the DropZone will reset and lose all items, I have tried to refresh it with the InputEvent without success, can you confirm if this is a limitation, or am I doing something wrong?

Before Scroll
<img width="523" alt="image" src="https://user-images.githubusercontent.com/3724826/211831239-665f3c90-61d3-42e2-bbd5-55de0ff16049.png">

After Scroll
<img width="527" alt="image" src="https://user-images.githubusercontent.com/3724826/211831407-d75300e7-c659-49d7-a260-3169cfe6d068.png">

**Comment by scottdurow** [comment]
Hi @rsantos00,
Because galleries in Power Apps will destroy the controls that are scrolled off screen, this is expected.

You will need to update the source collection inside the OnDrop event similar to how I show in this series of videos - https://youtube.com/playlist?list=PLhgOm-Jpmt82JvLdJFx3Zqo89h_deWJQF

This means that when the DropZone is scrolled back into view, it is updated with the new items accordingly to their new DropZone location.

Hope this helps.
Thanks for supporting PowerDragDrop!

Scott

**Comment by rsantos00** [comment]
Awesome, thanks Scott, will check all the videos
