### ISSUE TITLE
How do I trigger OnSelect property?

### ISSUE THREAD

**Issue by matthewdevaney** [scottdurow/power-drag-drop#8]
Quick question:
How do I trigger the _OnSelect_ property of the component?  I assumed it would behave like a gallery - clicking on any item will trigger an OnSelect.  But the Notify function I used in the component doesn't fire.

![image](https://user-images.githubusercontent.com/34290969/204962594-9ab04a5e-5f33-4a5d-a25a-6830f68d8f11.png)

**Comment by harjitsamra** [comment]
Button clicks use the OnAction event - it's mentioned at the bottom of the README.md

**Comment by scottdurow** [comment]
Hi @matthewdevaney -  The `PowerDragDrop` control isn't like a gallery in that the items displayed are not guaranteed to always be in the `Items` collection if they have been dragged from a different zone.
Because of this, it doesn't support the `OnSelect` event (it's built-in and I can't remove it) since the `SelectedItem` property requires that the item being selected always be in the `Items` collection.

What is the scenario you are trying to implement?

**Comment by matthewdevaney** [comment]
@scottdurow
My goal is to make a simple Kanban that includes CRUD operations. I’ve been able to do that using the OnAction property. But I also saw the OnSelect property and wondered if it was possible to use.

Now that I know OnSelect is only there because it cannot be removed I will stop trying to use it 😊
